import Footer from "@/components/footer";
import Hero from "@/components/hero";
import { Inter } from "next/font/google";
import "../globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="max-w-7xl mx-auto bg-red-200"> logo a menu</header>
        <main className="flex min-h-96 flex-col items-center justify-between p-24 max-w-7xl mx-auto bg-green-200">
          {children}
        </main>
      </body>
    </html>
  );
}
